project:
  type: website
  resources:
    - 3d_files/
    - figures/

website:
  title: "ASMS 3D 2023"
  back-to-top-navigation: true
  search: false
  navbar:
    foreground: "#FFFFFF"
    background: "#6D000F"
    left:
      - text: MS
        url: index.html#category-ms
      - text: Labware
        url: index.html#category-labware
      - text: Educational
        url: index.html#category-educational

format:
  html:
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    code-fold: true
    echo: false
    theme:
      - darkly
      - custom.scss
    css:
      - custom.css
